// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ArticleLeft: typeof import('./src/components/ArticleLeft/index.vue')['default']
    ArticleRight: typeof import('./src/components/ArticleRight/index.vue')['default']
    CardList: typeof import('./src/components/Card-list/index.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElRow: typeof import('element-plus/es')['ElRow']
    Input: typeof import('./src/components/Header/Input/index.vue')['default']
    LoginAndRegist: typeof import('./src/components/Header/LoginAndRegist/index.vue')['default']
    Menu: typeof import('./src/components/Header/Menu/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Swiper: typeof import('./src/components/Swiper/index.vue')['default']
  }
}
